server {
    listen 80;
    server_name gl-cdl.com www.gl-cdl.com;

    root /path/to/react/build;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass https://cdlbackend-lagfzewagq-ue.a.run.app/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name greatlakescdlacademy.net www.greatlakescdlacademy.net;

    root /path/to/react/build;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass https://cdlbackend-lagfzewagq-ue.a.run.app/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
